name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3.1.0
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
